const colors = {
  light: {
    text: "#0F1C2E",
    tint: "#2B7FFF",
    background: "#FFFFFF",
    foreground: "#0F1C2E",
    card: "#F0F6FF",
    cardForeground: "#0F1C2E",
    cardElevated: "#E3EEFF",
    primary: "#2B7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#5A9FFF",
    secondaryForeground: "#FFFFFF",
    muted: "#EBF3FF",
    mutedForeground: "#4A5568",
    accent: "#EBF3FF",
    accentForeground: "#0F1C2E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    save: "#5A9FFF",
    border: "#E2EAFF",
    input: "#E2EAFF",
    saffron: "#F59E0B",
    herbGreen: "#10B981",
    skipRed: "#EF4444",
    saveBlue: "#2B7FFF",
    overlay: "rgba(0,0,0,0.4)",
    tabBar: "#FFFFFF",
    textPrimary: "#0F1C2E",
    textSecondary: "#4A5568",
    textMuted: "#94A3B8",
  },
  dark: {
    text: "#E8F0FF",
    tint: "#4D8FFF",
    background: "#07101E",
    foreground: "#E8F0FF",
    card: "#0E1929",
    cardForeground: "#E8F0FF",
    cardElevated: "#152236",
    primary: "#4D8FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#6BA3FF",
    secondaryForeground: "#FFFFFF",
    muted: "#0A1520",
    mutedForeground: "#5A7090",
    accent: "#0A1520",
    accentForeground: "#E8F0FF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    save: "#6BA3FF",
    border: "#18293F",
    input: "#18293F",
    saffron: "#F59E0B",
    herbGreen: "#10B981",
    skipRed: "#EF4444",
    saveBlue: "#4D8FFF",
    overlay: "rgba(0,0,0,0.7)",
    tabBar: "#07101E",
    textPrimary: "#E8F0FF",
    textSecondary: "#8BAAC8",
    textMuted: "#3D5468",
  },
  radius: 16,
};

export default colors;
