export const STORAGE_KEYS = {
  PROFILE:              "pantryswipe_profile",
  PANTRY:               "pantryswipe_pantry",
  SAVED:                "pantryswipe_saved",
  COOKED:               "pantryswipe_cooked",
  STATS:                "pantryswipe_stats",
  SETUP_COMPLETE:       "pantryswipe_setup_complete",
  COOKING_HISTORY:      "pantryswipe_cooking_history",
  LEARNING:             "pantryswipe_learning",
  SETTINGS:             "pantryswipe_settings",
  TUTORIAL_SEEN:        "swipeTutorialSeen",
  PENDING_INTENT:       "@pantryswipe:pendingIntent",
  AUTH_TOKEN:           "pantryswipe_auth_token",
  SOCIAL_FOLLOWING:     "pantryswipe_social_following",
  SOCIAL_SAVED_POSTS:   "pantryswipe_social_saved_posts",
} as const;
