/**
 * Smart emoji lookup for pantry items.
 * Tries to match item name keywords → specific food emoji.
 * Falls back to category-appropriate emoji when no match is found.
 */

// ── Category fallbacks ────────────────────────────────────────────────────────
const CATEGORY_FALLBACK: Record<string, string> = {
  Fridge: "🧀",
  Freezer: "❄️",
  Pantry: "🥫",
  Spices: "🌶️",
  Sauces: "🫙",
  Beverages: "🍷",
  Produce: "🥦",
  // scanning categories
  dairy: "🥛",
  produce: "🥦",
  meat: "🥩",
  seafood: "🐟",
  frozen: "❄️",
  grains: "🌾",
  condiments: "🫙",
  sauces: "🫙",
  spices: "🌶️",
  drinks: "🍷",
  snacks: "🍫",
  baking: "🥄",
  other: "📦",
};

// ── Keyword → emoji map ───────────────────────────────────────────────────────
// Ordered longest-first so "sweet potato" matches before "potato"
const KEYWORD_EMOJI: [string, string][] = [
  // ── Fruit ──
  ["strawberr", "🍓"],
  ["blueberr", "🫐"],
  ["raspberr", "🍓"],
  ["blackberr", "🍓"],
  ["cranberr", "🍓"],
  ["gooseberr", "🍓"],
  ["watermelon", "🍉"],
  ["cantaloupe", "🍈"],
  ["honeydew", "🍈"],
  ["pineapple", "🍍"],
  ["pomegranate", "🍎"],
  ["grapefruit", "🍊"],
  ["clementine", "🍊"],
  ["mandarin", "🍊"],
  ["tangerine", "🍊"],
  ["passion fruit", "🍈"],
  ["dragonfruit", "🍈"],
  ["sweet potato", "🍠"],
  ["butternut", "🥕"],
  ["avocado", "🥑"],
  ["coconut", "🥥"],
  ["plantain", "🍌"],
  ["banana", "🍌"],
  ["orange", "🍊"],
  ["lemon", "🍋"],
  ["lime", "🍋"],
  ["mango", "🥭"],
  ["papaya", "🥭"],
  ["cherry", "🍒"],
  ["grape", "🍇"],
  ["raisin", "🍇"],
  ["peach", "🍑"],
  ["nectarine", "🍑"],
  ["apricot", "🍑"],
  ["plum", "🍑"],
  ["prune", "🍑"],
  ["pear", "🍐"],
  ["apple", "🍎"],
  ["kiwi", "🥝"],
  ["fig", "🍈"],
  ["date", "🍈"],
  ["melon", "🍈"],
  ["guava", "🍈"],
  ["lychee", "🍈"],
  ["quince", "🍈"],
  // ── Vegetables ──
  ["broccoli", "🥦"],
  ["cauliflower", "🥦"],
  ["brussels sprout", "🥦"],
  ["artichoke", "🥦"],
  ["asparagus", "🥦"],
  ["broccolini", "🥦"],
  ["spinach", "🥬"],
  ["lettuce", "🥬"],
  ["kale", "🥬"],
  ["cabbage", "🥬"],
  ["bok choy", "🥬"],
  ["chard", "🥬"],
  ["arugula", "🥬"],
  ["watercress", "🥬"],
  ["collard", "🥬"],
  ["radicchio", "🥬"],
  ["endive", "🥬"],
  ["eggplant", "🍆"],
  ["aubergine", "🍆"],
  ["cucumber", "🥒"],
  ["zucchini", "🥒"],
  ["courgette", "🥒"],
  ["tomato", "🍅"],
  ["peppadew", "🫑"],
  ["capsicum", "🫑"],
  ["bell pepper", "🫑"],
  ["pepper", "🫑"],
  ["chili", "🌶️"],
  ["chilli", "🌶️"],
  ["jalapeño", "🌶️"],
  ["jalapeno", "🌶️"],
  ["habanero", "🌶️"],
  ["serrano", "🌶️"],
  ["potato", "🥔"],
  ["yam", "🍠"],
  ["shallot", "🧅"],
  ["onion", "🧅"],
  ["leek", "🧅"],
  ["scallion", "🧅"],
  ["spring onion", "🧅"],
  ["green onion", "🧅"],
  ["chive", "🧅"],
  ["garlic", "🧄"],
  ["ginger", "🫚"],
  ["turmeric", "🌶️"],
  ["carrot", "🥕"],
  ["parsnip", "🥕"],
  ["turnip", "🥕"],
  ["radish", "🥕"],
  ["beet", "🥕"],
  ["beetroot", "🥕"],
  ["celery", "🥬"],
  ["fennel", "🥬"],
  ["corn", "🌽"],
  ["maize", "🌽"],
  ["sweetcorn", "🌽"],
  ["pea", "🫛"],
  ["edamame", "🫛"],
  ["snap pea", "🫛"],
  ["bean", "🫘"],
  ["lentil", "🫘"],
  ["chickpea", "🫘"],
  ["mushroom", "🍄"],
  ["truffle", "🍄"],
  ["pumpkin", "🎃"],
  ["squash", "🥕"],
  // ── Meat ──
  ["chicken", "🍗"],
  ["turkey", "🍗"],
  ["duck", "🍗"],
  ["poultry", "🍗"],
  ["breast", "🍗"],
  ["thigh", "🍗"],
  ["wing", "🍗"],
  ["drumstick", "🍗"],
  ["bacon", "🥓"],
  ["ham", "🥓"],
  ["prosciutto", "🥓"],
  ["pancetta", "🥓"],
  ["salami", "🥓"],
  ["pepperoni", "🥓"],
  ["chorizo", "🥓"],
  ["sausage", "🌭"],
  ["bratwurst", "🌭"],
  ["hot dog", "🌭"],
  ["wiener", "🌭"],
  ["frank", "🌭"],
  ["steak", "🥩"],
  ["beef", "🥩"],
  ["pork", "🥩"],
  ["lamb", "🥩"],
  ["veal", "🥩"],
  ["mince", "🥩"],
  ["ground meat", "🥩"],
  ["ground beef", "🥩"],
  ["ground pork", "🥩"],
  ["brisket", "🥩"],
  ["rib", "🥩"],
  ["roast", "🥩"],
  ["tenderloin", "🥩"],
  ["sirloin", "🥩"],
  ["venison", "🥩"],
  // ── Seafood ──
  ["salmon", "🐟"],
  ["tuna", "🐟"],
  ["cod", "🐟"],
  ["halibut", "🐟"],
  ["tilapia", "🐟"],
  ["trout", "🐟"],
  ["bass", "🐟"],
  ["haddock", "🐟"],
  ["flounder", "🐟"],
  ["sole", "🐟"],
  ["catfish", "🐟"],
  ["mackerel", "🐟"],
  ["anchovy", "🐟"],
  ["sardine", "🐟"],
  ["herring", "🐟"],
  ["mahi", "🐟"],
  ["snapper", "🐟"],
  ["swordfish", "🐟"],
  ["fish", "🐟"],
  ["shrimp", "🦐"],
  ["prawn", "🦐"],
  ["crab", "🦀"],
  ["lobster", "🦞"],
  ["crayfish", "🦞"],
  ["scallop", "🦀"],
  ["mussel", "🦪"],
  ["clam", "🦪"],
  ["oyster", "🦪"],
  ["squid", "🦑"],
  ["calamari", "🦑"],
  ["octopus", "🐙"],
  // ── Dairy ──
  ["whole milk", "🥛"],
  ["skim milk", "🥛"],
  ["low-fat milk", "🥛"],
  ["milk", "🥛"],
  ["cream", "🥛"],
  ["yogurt", "🧈"],
  ["yoghurt", "🧈"],
  ["kefir", "🥛"],
  ["buttermilk", "🥛"],
  ["mozzarella", "🧀"],
  ["cheddar", "🧀"],
  ["parmesan", "🧀"],
  ["brie", "🧀"],
  ["feta", "🧀"],
  ["gouda", "🧀"],
  ["ricotta", "🧀"],
  ["camembert", "🧀"],
  ["gruyere", "🧀"],
  ["goat cheese", "🧀"],
  ["cream cheese", "🧀"],
  ["cheese", "🧀"],
  ["butter", "🧈"],
  ["ghee", "🧈"],
  ["margarine", "🧈"],
  ["egg", "🥚"],
  // ── Bread & Grains ──
  ["sourdough", "🍞"],
  ["baguette", "🥖"],
  ["croissant", "🥐"],
  ["bagel", "🥯"],
  ["pita", "🫓"],
  ["flatbread", "🫓"],
  ["naan", "🫓"],
  ["tortilla", "🫓"],
  ["wrap", "🫓"],
  ["bread", "🍞"],
  ["bun", "🍞"],
  ["roll", "🍞"],
  ["toast", "🍞"],
  ["waffle", "🧇"],
  ["pancake", "🥞"],
  ["crepe", "🥞"],
  ["pasta", "🍝"],
  ["spaghetti", "🍝"],
  ["fettuccine", "🍝"],
  ["penne", "🍝"],
  ["linguine", "🍝"],
  ["lasagna", "🍝"],
  ["noodle", "🍜"],
  ["ramen", "🍜"],
  ["udon", "🍜"],
  ["rice", "🍚"],
  ["quinoa", "🌾"],
  ["oat", "🌾"],
  ["porridge", "🌾"],
  ["granola", "🌾"],
  ["cereal", "🌾"],
  ["muesli", "🌾"],
  ["flour", "🌾"],
  ["wheat", "🌾"],
  ["barley", "🌾"],
  ["rye", "🌾"],
  ["couscous", "🌾"],
  ["bulgur", "🌾"],
  ["polenta", "🌾"],
  ["cornmeal", "🌾"],
  // ── Condiments & Sauces ──
  ["ketchup", "🍅"],
  ["mustard", "🫙"],
  ["mayo", "🥚"],
  ["mayonnaise", "🥚"],
  ["hot sauce", "🌶️"],
  ["sriracha", "🌶️"],
  ["tabasco", "🌶️"],
  ["soy sauce", "🫙"],
  ["tamari", "🫙"],
  ["worcestershire", "🫙"],
  ["teriyaki", "🫙"],
  ["hoisin", "🫙"],
  ["oyster sauce", "🫙"],
  ["fish sauce", "🫙"],
  ["vinegar", "🫙"],
  ["salsa", "🍅"],
  ["guacamole", "🥑"],
  ["hummus", "🫘"],
  ["tzatziki", "🫙"],
  ["aioli", "🧄"],
  ["pesto", "🌿"],
  ["tahini", "🫙"],
  ["relish", "🫙"],
  ["pickle", "🫙"],
  ["jam", "🍓"],
  ["jelly", "🍓"],
  ["marmalade", "🍊"],
  ["honey", "🍯"],
  ["syrup", "🍯"],
  ["maple", "🍯"],
  ["agave", "🍯"],
  ["peanut butter", "🥜"],
  ["almond butter", "🥜"],
  ["nutella", "🍫"],
  ["marmite", "🫙"],
  ["vegemite", "🫙"],
  // ── Oils & Fats ──
  ["olive oil", "🫒"],
  ["coconut oil", "🥥"],
  ["sesame oil", "🫚"],
  ["oil", "🫚"],
  // ── Spices & Herbs ──
  ["salt", "🧂"],
  ["pepper", "🌶️"],
  ["cinnamon", "🫙"],
  ["cumin", "🌶️"],
  ["paprika", "🌶️"],
  ["cayenne", "🌶️"],
  ["oregano", "🌿"],
  ["basil", "🌿"],
  ["thyme", "🌿"],
  ["rosemary", "🌿"],
  ["dill", "🌿"],
  ["parsley", "🌿"],
  ["cilantro", "🌿"],
  ["coriander", "🌿"],
  ["mint", "🌿"],
  ["sage", "🌿"],
  ["tarragon", "🌿"],
  ["bay leaf", "🌿"],
  ["nutmeg", "🫙"],
  ["cardamom", "🫙"],
  ["clove", "🫙"],
  ["star anise", "🫙"],
  ["allspice", "🫙"],
  ["saffron", "🌼"],
  ["vanilla", "🍦"],
  ["sumac", "🌶️"],
  ["za'atar", "🌿"],
  // ── Drinks ──
  ["coffee", "☕"],
  ["espresso", "☕"],
  ["latte", "☕"],
  ["tea", "🍵"],
  ["green tea", "🍵"],
  ["matcha", "🍵"],
  ["beer", "🍺"],
  ["ale", "🍺"],
  ["lager", "🍺"],
  ["wine", "🍷"],
  ["champagne", "🍾"],
  ["prosecco", "🍾"],
  ["cider", "🍺"],
  ["juice", "🧃"],
  ["lemonade", "🍋"],
  ["smoothie", "🧃"],
  ["soda", "🥤"],
  ["cola", "🥤"],
  ["water", "💧"],
  ["kombucha", "🫙"],
  ["milk", "🥛"],
  // ── Snacks ──
  ["chip", "🍟"],
  ["crisp", "🍟"],
  ["cracker", "🫙"],
  ["pretzel", "🥨"],
  ["popcorn", "🍿"],
  ["nuts", "🥜"],
  ["peanut", "🥜"],
  ["almond", "🥜"],
  ["walnut", "🥜"],
  ["cashew", "🥜"],
  ["pistachio", "🥜"],
  ["pecan", "🥜"],
  ["hazelnut", "🥜"],
  ["chocolate", "🍫"],
  ["candy", "🍬"],
  ["gummy", "🍬"],
  ["cookie", "🍪"],
  ["biscuit", "🍪"],
  ["brownie", "🍫"],
  // ── Baking ──
  ["sugar", "🍚"],
  ["brown sugar", "🍚"],
  ["icing sugar", "🍚"],
  ["baking powder", "🥄"],
  ["baking soda", "🥄"],
  ["yeast", "🍞"],
  ["cocoa", "🍫"],
  ["chocolate chip", "🍫"],
  ["sprinkle", "🎂"],
  // ── Frozen & Convenience ──
  ["ice cream", "🍦"],
  ["gelato", "🍦"],
  ["frozen", "❄️"],
  ["pizza", "🍕"],
  ["burger", "🍔"],
  ["nugget", "🍗"],
  ["dumpling", "🥟"],
  ["gyoza", "🥟"],
  ["spring roll", "🥟"],
  ["tofu", "🫙"],
  ["tempeh", "🫘"],
  ["soup", "🍲"],
  ["broth", "🍲"],
  ["stock", "🍲"],
];

/**
 * Returns the best emoji for the given item name and optional category.
 */
export function getItemEmoji(name: string, category?: string): string {
  const lower = name.toLowerCase().trim();

  for (const [keyword, emoji] of KEYWORD_EMOJI) {
    if (lower.includes(keyword)) return emoji;
  }

  // category fallback
  if (category && CATEGORY_FALLBACK[category]) return CATEGORY_FALLBACK[category];

  return "🛒";
}
